version: "3"
services:
  holden:
    container_name: holden
    image: ghcr.io/endigma/holden
    build: .
    volumes:
      - ./docs:/docs
      - ./example.toml:/config.toml
    ports:
      - "11011:11011"