[general]
# the folder which markdown files are served from, 
# can be absolute or workdir relative (no trailing slash)
# set to `_binary` to use binary parent folder
docroot = "docs"
# webserver port
port = "11011"
# use prefixes, for when you for example want to 
# proxy it under a subdirectory (no trailing slash)
prefix = ""
# specify the working directory used by the program for 
# its own resources (this must contain assets/) (append trailing slash)
# leave empty to assume running workdir
# set to `_binary` to use binary parent folder
workdir = ""
# allow unsanitized html from the markdown file to be rendered
allowhtml = false
# make lines in code blocks linkable (add ids to them)
linkablelines = true
# if the user agent is curl and a raw file is being accessed, render it with ansi escape sequences
fancycurl = true
# print debug info to stdout
debug = false
# fancystdout colorizes and does other cool stuff to logs
fancystdout = true

[website]
# the name that will appear in the auto generated sidebar, leave empty for none
sitename = ""
# display back to top button
backtotop = true
# display sidebar
sidebar = true

[aesthetic]
# theme for fenced code blocks, one of https://xyproto.github.io/splash/docs/all.html
highlightstyle = "solarized-dark256"
# enable/disable line numbers in code blocks
linenumbers = true
# separate line numbers into a table so you can copy-paste code easier
linenumbersintable = true
# sets the width of a tab
tabwidth = 4
# determines whether the syntax highlighter uses class names or hardcoded css
# if you enable this it renders highlightstyle useless
useclasses = false
